# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: be-ci

on:
  push:
    branches: [ "main" ]
    paths:
      - "BE/**"
      - ".github/workflows/be-ci.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "BE/**"

jobs:
  build-and-test:                 # Job 1
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./BE

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore BookStore.sln

      - name: Build
        run: dotnet build BookStore.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test Core/BookStore.Tests/BookStore.Tests.csproj --configuration Release --verbosity normal

  build-and-push-image:          # Job 2 (cùng cấp với build-and-test)
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'   # chỉ chạy khi push lên main
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        env:
          IMAGE_NAME: ghcr.io/${{ toLower(github.repository) }}-be
          TAG: prod
        run: |
          echo "Building image: $IMAGE_NAME:$TAG"
          docker build -f BE/Dockerfile -t $IMAGE_NAME:$TAG ./BE
          docker push $IMAGE_NAME:$TAG
